#!/usr/bin/env bash
set -euo pipefail

ROOT="/workspaces/StormTracker"
cd "$ROOT"

echo "StormTracker — Core V4 sync/fallback fix"

for f in frontend/src/live3d-core-v3.js frontend/live3d-core-v3.html; do
  if [ ! -f "$f" ]; then echo "ERROR: Missing required file: $f"; exit 1; fi
done

cp frontend/src/live3d-core-v3.js frontend/src/live3d-core-v4.js
cp frontend/live3d-core-v3.html frontend/live3d-core-v4.html

cat > /tmp/stormtracker_replace_b64.py <<'PY'
import base64, sys
from pathlib import Path
path=Path(sys.argv[1]); mode=sys.argv[2]
old=base64.b64decode(sys.argv[3]).decode()
new=base64.b64decode(sys.argv[4]).decode()
text=path.read_text(encoding='utf-8')
count=text.count(old)
if count == 0:
    raise SystemExit(f'ERROR: patch target not found in {path}: {old[:80]!r}')
if mode == 'once':
    text=text.replace(old,new,1)
elif mode == 'all':
    text=text.replace(old,new)
else:
    raise SystemExit('bad mode')
path.write_text(text,encoding='utf-8')
print(f'{path}: replaced {1 if mode=="once" else count} occurrence(s)')
PY

python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once bGV0IGh5YnJpZFRyYWNrVm9sdW1lQ29sbGVjdGlvbiA9IG51bGw7 bGV0IGh5YnJpZFRyYWNrVm9sdW1lQ29sbGVjdGlvbiA9IG51bGw7CgovLyBQcmV2ZW50IGFuIG9sZGVyIGFzeW5jaHJvbm91cyByYWRhci1pbWFnZSBsb2FkIGZyb20gcmVwbGFjaW5nIGEgbmV3ZXIKLy8gZnJhbWUgYWZ0ZXIgcmFwaWQgc2NydWJiaW5nL3BsYXliYWNrLgpsZXQgaHlicmlkU2NlbmVSZW5kZXJUb2tlbiA9IDA7
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once YXN5bmMgZnVuY3Rpb24gcmVuZGVyU3VyZmFjZShmcmFtZSkgew== YXN5bmMgZnVuY3Rpb24gcmVuZGVyU3VyZmFjZSgKICBmcmFtZSwKICByZW5kZXJUb2tlbiA9IG51bGwKKSB7
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once ICBpZiAoc3VyZmFjZUxheWVyKSB7CiAgICB2aWV3ZXIuaW1hZ2VyeUxheWVycy5yZW1vdmUoCiAgICAgIHN1cmZhY2VMYXllciwKICAgICAgdHJ1ZQogICAgKTsKICB9CgogIHN1cmZhY2VMYXllciA9CiAgICBuZXcgQ2VzaXVtLkltYWdlcnlMYXllcigKICAgICAgcHJvdmlkZXIKICAgICk7CgogIHN1cmZhY2VMYXllci5hbHBoYSA9CiAgICAwLjY1OwoKICB2aWV3ZXIuaW1hZ2VyeUxheWVycy5hZGQoCiAgICBzdXJmYWNlTGF5ZXIKICApOwp9 ICBpZiAoCiAgICByZW5kZXJUb2tlbiAhPSBudWxsCiAgICAmJiByZW5kZXJUb2tlbiAhPT0gaHlicmlkU2NlbmVSZW5kZXJUb2tlbgogICkgewogICAgcmV0dXJuIGZhbHNlOwogIH0KCiAgaWYgKHN1cmZhY2VMYXllcikgewogICAgdmlld2VyLmltYWdlcnlMYXllcnMucmVtb3ZlKAogICAgICBzdXJmYWNlTGF5ZXIsCiAgICAgIHRydWUKICAgICk7CiAgfQoKICBzdXJmYWNlTGF5ZXIgPQogICAgbmV3IENlc2l1bS5JbWFnZXJ5TGF5ZXIoCiAgICAgIHByb3ZpZGVyCiAgICApOwoKICBzdXJmYWNlTGF5ZXIuYWxwaGEgPQogICAgMC42NTsKCiAgdmlld2VyLmltYWdlcnlMYXllcnMuYWRkKAogICAgc3VyZmFjZUxheWVyCiAgKTsKCiAgc2NlbmUucmVxdWVzdFJlbmRlcigpOwoKICByZXR1cm4gdHJ1ZTsKfQ==
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once ZnVuY3Rpb24gY2xlYXJIeWJyaWRUcmFja1ZvbHVtZUNvbGxlY3Rpb24oKSB7 ZnVuY3Rpb24gaGFzVHJhY2tTcGVjaWZpY1ZvbHVtZSgKICBpbmRleAopIHsKICByZXR1cm4gKAogICAgaHlicmlkVHJhY2tWb2x1bWVzW2luZGV4XQogICAgICA/LnNpemUKICAgID8/IDAKICApID4gMDsKfQoKZnVuY3Rpb24gdXNlVHJhY2tTcGVjaWZpY1ZvbHVtZSgKICBpbmRleAopIHsKICByZXR1cm4gKAogICAgQm9vbGVhbigKICAgICAgJCgic2hvd1RyYWNrVm9sdW1lcyIpCiAgICAgICAgPy5jaGVja2VkCiAgICApCiAgICAmJiBoYXNUcmFja1NwZWNpZmljVm9sdW1lKAogICAgICBpbmRleAogICAgKQogICk7Cn0KCmZ1bmN0aW9uIGFwcGx5SHlicmlkVm9sdW1lTW9kZSgKICBpbmRleAopIHsKICBjb25zdCB1c2VUcmFja1NwZWNpZmljID0KICAgIHVzZVRyYWNrU3BlY2lmaWNWb2x1bWUoCiAgICAgIGluZGV4CiAgICApOwoKICBpZiAoaW5mZXJyZWRDb2xsZWN0aW9uKSB7CiAgICBpbmZlcnJlZENvbGxlY3Rpb24uc2hvdyA9CiAgICAgICF1c2VUcmFja1NwZWNpZmljOwogIH0KCiAgY29uc3QgbW9kZSA9CiAgICAkKCJoeWJyaWRWb2x1bWVNb2RlIik7CgogIGlmIChtb2RlKSB7CiAgICBtb2RlLnRleHRDb250ZW50ID0KICAgICAgdXNlVHJhY2tTcGVjaWZpYwogICAgICAgID8gIk1lYXN1cmVkLXRyYWNrLXNwZWNpZmljIgogICAgICAgIDogKAogICAgICAgICAgICBCb29sZWFuKAogICAgICAgICAgICAgICQoInNob3dUcmFja1ZvbHVtZXMiKQogICAgICAgICAgICAgICAgPy5jaGVja2VkCiAgICAgICAgICAgICkKICAgICAgICAgICAgICA/ICJGcmFtZS13aWRlIGZhbGxiYWNrIChubyBtZWFzdXJlZCB0cmFjaykiCiAgICAgICAgICAgICAgOiAiRnJhbWUtd2lkZSBpbmZlcnJlZCIKICAgICAgICAgICk7CiAgfQoKICBzY2VuZS5yZXF1ZXN0UmVuZGVyKCk7CgogIHJldHVybiB1c2VUcmFja1NwZWNpZmljOwp9CgpmdW5jdGlvbiB0cmFja1BvaW50U2l6ZSgKICBzdXBwb3J0QmFuZAopIHsKICBjb25zdCBiYXNlID0KICAgIE51bWJlcigKICAgICAgJCgicG9pbnRTaXplIikudmFsdWUKICAgICk7CgogIGNvbnN0IHNjYWxlID0KICAgIHN1cHBvcnRCYW5kID09PSAiaGlnaCIKICAgICAgPyAxLjAKICAgICAgOiBzdXBwb3J0QmFuZCA9PT0gIm1lZGl1bSIKICAgICAgICA/IDAuODIKICAgICAgICA6IDAuNjI7CgogIHJldHVybiBNYXRoLm1heCgKICAgIDEuNSwKICAgIGJhc2UgKiBzY2FsZQogICk7Cn0KCmZ1bmN0aW9uIGNsZWFySHlicmlkVHJhY2tWb2x1bWVDb2xsZWN0aW9uKCkgew==
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once ICBjb25zdCBzaG93VHJhY2tWb2x1bWVzID0KICAgIEJvb2xlYW4oCiAgICAgICQoInNob3dUcmFja1ZvbHVtZXMiKQogICAgICAgID8uY2hlY2tlZAogICAgKTs= ICBjb25zdCBzaG93VHJhY2tWb2x1bWVzID0KICAgIHVzZVRyYWNrU3BlY2lmaWNWb2x1bWUoCiAgICAgIGluZGV4CiAgICApOw==
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once ICAgICAgICAgICAgcGl4ZWxTaXplOgogICAgICAgICAgICAgIHBvaW50LnBpeGVsX3NpemUs ICAgICAgICAgICAgcGl4ZWxTaXplOgogICAgICAgICAgICAgIHRyYWNrUG9pbnRTaXplKAogICAgICAgICAgICAgICAgcG9pbnQuc3VwcG9ydF9iYW5kCiAgICAgICAgICAgICAgKSw=
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once YXN5bmMgZnVuY3Rpb24gc2hvd0h5YnJpZEZyYW1lKGluZGV4KSB7CiAgaHlicmlkRnJhbWVJbmRleCA9 YXN5bmMgZnVuY3Rpb24gc2hvd0h5YnJpZEZyYW1lKGluZGV4KSB7CiAgY29uc3QgcmVuZGVyVG9rZW4gPQogICAgKytoeWJyaWRTY2VuZVJlbmRlclRva2VuOwoKICBoeWJyaWRGcmFtZUluZGV4ID0=
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once ICBhd2FpdCByZW5kZXJTdXJmYWNlKGZyYW1lKTsKCiAgcmVuZGVySW5mZXJyZWRWb2x1bWUoZnJhbWUpOwoKICBpZiAoCiAgICBpbmZlcnJlZENvbGxlY3Rpb24KICAgICYmIGh5YnJpZFJlc3VsdHMubGVuZ3RoCiAgKSB7CiAgICBpbmZlcnJlZENvbGxlY3Rpb24uc2hvdyA9CiAgICAgICFCb29sZWFuKAogICAgICAgICQoInNob3dUcmFja1ZvbHVtZXMiKQogICAgICAgICAgPy5jaGVja2VkCiAgICAgICk7CiAgfQoKICByZW5kZXJIeWJyaWRUcmFja3MoaHlicmlkRnJhbWVJbmRleCk7CiAgdXBkYXRlSHlicmlkU291cmNlTWV0cmljcyhmcmFtZSk7 ICBjb25zdCBzdXJmYWNlQXBwbGllZCA9CiAgICBhd2FpdCByZW5kZXJTdXJmYWNlKAogICAgICBmcmFtZSwKICAgICAgcmVuZGVyVG9rZW4KICAgICk7CgogIGlmICghc3VyZmFjZUFwcGxpZWQpIHsKICAgIHJldHVybjsKICB9CgogIHJlbmRlckluZmVycmVkVm9sdW1lKAogICAgZnJhbWUKICApOwoKICBhcHBseUh5YnJpZFZvbHVtZU1vZGUoCiAgICBoeWJyaWRGcmFtZUluZGV4CiAgKTsKCiAgcmVuZGVySHlicmlkVHJhY2tzKAogICAgaHlicmlkRnJhbWVJbmRleAogICk7CgogIHVwZGF0ZUh5YnJpZFNvdXJjZU1ldHJpY3MoCiAgICBmcmFtZQogICk7CgogIGNvbnN0IHNjZW5lRnJhbWUgPQogICAgJCgiaHlicmlkU2NlbmVGcmFtZSIpOwoKICBpZiAoc2NlbmVGcmFtZSkgewogICAgc2NlbmVGcmFtZS50ZXh0Q29udGVudCA9CiAgICAgIGZyYW1lLm9ic2VydmVkVXRjCiAgICAgICAgLnJlcGxhY2UoIlQiLCAiICIpCiAgICAgICAgLnJlcGxhY2UoIloiLCAiIFVUQyIpOwogIH0=
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once JCgic2hvd1RyYWNrVm9sdW1lcyIpLmFkZEV2ZW50TGlzdGVuZXIoCiAgImNoYW5nZSIsCiAgKCkgPT4gewogICAgaWYgKAogICAgICBpbmZlcnJlZENvbGxlY3Rpb24KICAgICAgJiYgaHlicmlkUmVzdWx0cy5sZW5ndGgKICAgICkgewogICAgICBpbmZlcnJlZENvbGxlY3Rpb24uc2hvdyA9CiAgICAgICAgIUJvb2xlYW4oCiAgICAgICAgICAkKCJzaG93VHJhY2tWb2x1bWVzIikKICAgICAgICAgICAgLmNoZWNrZWQKICAgICAgICApOwogICAgfQoKICAgIHJlbmRlckh5YnJpZFRyYWNrcygKICAgICAgaHlicmlkRnJhbWVJbmRleAogICAgKTsKICB9Cik7 JCgic2hvd1RyYWNrVm9sdW1lcyIpLmFkZEV2ZW50TGlzdGVuZXIoCiAgImNoYW5nZSIsCiAgKCkgPT4gewogICAgYXBwbHlIeWJyaWRWb2x1bWVNb2RlKAogICAgICBoeWJyaWRGcmFtZUluZGV4CiAgICApOwoKICAgIHJlbmRlckh5YnJpZFRyYWNrcygKICAgICAgaHlicmlkRnJhbWVJbmRleAogICAgKTsKICB9Cik7
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js all ICAgIGlmIChsYXRlc3RGcmFtZSkgewogICAgICByZW5kZXJJbmZlcnJlZFZvbHVtZSgKICAgICAgICBsYXRlc3RGcmFtZQogICAgICApOwogICAgfQ== ICAgIGlmIChsYXRlc3RGcmFtZSkgewogICAgICByZW5kZXJJbmZlcnJlZFZvbHVtZSgKICAgICAgICBsYXRlc3RGcmFtZQogICAgICApOwoKICAgICAgaWYgKGh5YnJpZFJlc3VsdHMubGVuZ3RoKSB7CiAgICAgICAgYXBwbHlIeWJyaWRWb2x1bWVNb2RlKAogICAgICAgICAgaHlicmlkRnJhbWVJbmRleAogICAgICAgICk7CgogICAgICAgIHJlbmRlckh5YnJpZFRyYWNrcygKICAgICAgICAgIGh5YnJpZEZyYW1lSW5kZXgKICAgICAgICApOwogICAgICB9CiAgICB9
python3 /tmp/stormtracker_replace_b64.py frontend/src/live3d-core-v4.js once ICBhd2FpdCByZW5kZXJTdXJmYWNlKAogICAgZnJhbWUKICApOwoKICByZW5kZXJJbmZlcnJlZFZvbHVtZSgKICAgIGZyYW1lCiAgKTs= ICBjb25zdCByZW5kZXJUb2tlbiA9CiAgICArK2h5YnJpZFNjZW5lUmVuZGVyVG9rZW47CgogIGNvbnN0IHN1cmZhY2VBcHBsaWVkID0KICAgIGF3YWl0IHJlbmRlclN1cmZhY2UoCiAgICAgIGZyYW1lLAogICAgICByZW5kZXJUb2tlbgogICAgKTsKCiAgaWYgKCFzdXJmYWNlQXBwbGllZCkgewogICAgcmV0dXJuOwogIH0KCiAgcmVuZGVySW5mZXJyZWRWb2x1bWUoCiAgICBmcmFtZQogICk7
python3 /tmp/stormtracker_replace_b64.py frontend/live3d-core-v4.html once U3Rvcm1UcmFja2VyIOKAlCBIeWJyaWQgU3Rvcm0gVm9sdW1lIENvcmUgVjM= U3Rvcm1UcmFja2VyIOKAlCBIeWJyaWQgU3Rvcm0gVm9sdW1lIENvcmUgVjQ=
python3 /tmp/stormtracker_replace_b64.py frontend/live3d-core-v4.html once dHJhY2stc3BlY2lmaWMgaW5mZXJyZWQgdmVydGljYWwgdm9sdW1lcyDigKIgY29yZSBWMw== dHJhY2stc3BlY2lmaWMgaW5mZXJyZWQgdmVydGljYWwgdm9sdW1lcyDigKIgc2FtZS1mcmFtZSByZW5kZXJpbmcg4oCiIGNvcmUgVjQ=
python3 /tmp/stormtracker_replace_b64.py frontend/live3d-core-v4.html once c3JjPSIuL3NyYy9saXZlM2QtY29yZS12My5qcyI= c3JjPSIuL3NyYy9saXZlM2QtY29yZS12NC5qcyI=
python3 /tmp/stormtracker_replace_b64.py frontend/live3d-core-v4.html once U2hvdyBvbmx5IHRyYWNrLXNwZWNpZmljIGluZmVycmVkIDMtRCB2b2x1bWVzIGR1cmluZyBzZXF1ZW5jZQ== UHJlZmVyIHRyYWNrLXNwZWNpZmljIGluZmVycmVkIDMtRCB2b2x1bWVzIHdoZW4gYSBtZWFzdXJlZCB0cmFjayBleGlzdHM=
python3 /tmp/stormtracker_replace_b64.py frontend/live3d-core-v4.html once ICAgICAgICA8c3Bhbj5QZXJzaXN0ZW50IHRyYWNrcyDiiaUzIHNjYW5zPC9zcGFuPgogICAgICAgIDxzdHJvbmcgaWQ9Imh5YnJpZFBlcnNpc3RlbnRDb3VudCI+MDwvc3Ryb25nPg== ICAgICAgICA8c3Bhbj5QZXJzaXN0ZW50IHRyYWNrcyDiiaUzIHNjYW5zPC9zcGFuPgogICAgICAgIDxzdHJvbmcgaWQ9Imh5YnJpZFBlcnNpc3RlbnRDb3VudCI+MDwvc3Ryb25nPgoKICAgICAgICA8c3Bhbj4zLUQgZGlzcGxheSBtb2RlPC9zcGFuPgogICAgICAgIDxzdHJvbmcgaWQ9Imh5YnJpZFZvbHVtZU1vZGUiPuKAlDwvc3Ryb25nPgoKICAgICAgICA8c3Bhbj5TY2VuZSBmcmFtZTwvc3Bhbj4KICAgICAgICA8c3Ryb25nIGlkPSJoeWJyaWRTY2VuZUZyYW1lIj7igJQ8L3N0cm9uZz4=

echo aW1wb3J0IGFzc2VydCBmcm9tICJub2RlOmFzc2VydC9zdHJpY3QiOwoKZnVuY3Rpb24gbW9kZShwcmVmZXJUcmFja1NwZWNpZmljLCB0cmFja1ZvbHVtZUNvdW50KSB7CiAgcmV0dXJuICgKICAgIHByZWZlclRyYWNrU3BlY2lmaWMKICAgICYmIHRyYWNrVm9sdW1lQ291bnQgPiAwCiAgKQogICAgPyAidHJhY2stc3BlY2lmaWMiCiAgICA6ICJmcmFtZS13aWRlIjsKfQoKYXNzZXJ0LmVxdWFsKG1vZGUodHJ1ZSwgMCksICJmcmFtZS13aWRlIik7CmFzc2VydC5lcXVhbChtb2RlKHRydWUsIDEpLCAidHJhY2stc3BlY2lmaWMiKTsKYXNzZXJ0LmVxdWFsKG1vZGUoZmFsc2UsIDEpLCAiZnJhbWUtd2lkZSIpOwphc3NlcnQuZXF1YWwobW9kZShmYWxzZSwgMCksICJmcmFtZS13aWRlIik7Cgpjb25zb2xlLmxvZygiNCBDb3JlIFY0IHN5bmMvZmFsbGJhY2sgdGVzdHMgcGFzc2VkLiIpOwo= | base64 -d > frontend/tests/run-core-v4-sync-tests.mjs

echo
echo "Checking syntax..."
node --check frontend/src/live3d-core-v4.js
echo
echo "Running Core V4 tests..."
node frontend/tests/run-core-v4-sync-tests.mjs
echo
echo "Running existing relevant tests..."
node frontend/tests/run-measured-track-volume-tests.mjs
node frontend/tests/run-inferred-confidence-tests.mjs
node frontend/tests/run-inferred-volume-tests.mjs
node frontend/tests/run-node-tests.mjs
echo
echo "SUCCESS"
echo "Expected:"
echo "  4 Core V4 sync/fallback tests passed."
echo "  8 measured-track-volume tests passed."
echo "  5 inferred-confidence tests passed."
echo "  4 inferred-volume tests passed."
echo "  14 tests passed."
echo
echo "Commit and push:"
echo 'git add frontend/src/live3d-core-v4.js frontend/live3d-core-v4.html frontend/tests/run-core-v4-sync-tests.mjs' 
echo 'git commit -m "Fix hybrid 3-D frame synchronisation and zero-track fallback"' 
echo 'git push' 
echo
echo "After Pages deploys, open:"
echo "https://blakesmith-intel.github.io/StormTracker/live3d-core-v4.html"
echo
echo "Press: Load 30-min hybrid storm sequence"
echo "Do not touch the point-size slider initially."
echo "Confirm 3-D appears immediately and Scene frame matches Source time."
